[workspace]
members = [
    "five",
    "five_core",
    "test"
]

[workspace.package]
version = "0.1.4"
edition = "2021"
authors = ["runefs"]
description = "A rust crate to support DCI natively in rust"
license = "MIT" 
repository = "https://github.com/yourusername/five"